version: '3.8'

services:
  crowdsec-monitor-api:
    image: ghcr.io/jgeek00/crowdsec-monitor-api:latest
    container_name: crowdsec-monitor-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CROWDSEC_LAPI_URL=http://localhost:8080
      - CROWDSEC_USER=crowdsec_user
      - CROWDSEC_PASSWORD=crowdsec_password
      - DB_PATH=/app/database/crowdsec.db
      - SYNC_SCHEDULE=*/5 * * * * # Optional, default is every 5 minutes
      - DATA_RETENTION=2w # Optional, default is indefinite
      - API_PASSWORD= # Optional, leave empty to disable authentication
      - RATE_LIMIT= # Optional, format: <requests>/<minutes>, leave empty to disable rate limiting
    volumes:
      - ./database:/app/database
